package com.softII.vista;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import com.softII.controlador.ControladorArticuloCompra;
import com.softII.controlador.ControladorCliente;
import com.softII.controlador.ControladorGestionArticulos;
import com.softII.dominio.Articulo;
import com.softII.dominio.Categoria;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import java.awt.Component;

/**
 *
 * @author JuRiAnU
 */
public class GestionArticulos extends JDialog {

	/**
	 * Creates new form agregarArticulo
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton agregar;
	private javax.swing.JButton agregarCat;
	private javax.swing.JTextField autorText;
	private javax.swing.JButton buscar;
	private javax.swing.JButton cancelar;
	private javax.swing.JList categoriaList;
	private javax.swing.JComboBox categoria;
	private javax.swing.JTextArea descripcionArea;
	private javax.swing.JComboBox disponibleBox;
	private javax.swing.JButton editar;
	private javax.swing.JButton eliminarCat;
	private javax.swing.JComboBox estadoBox;
	private javax.swing.JComboBox formatoBox;
	private javax.swing.JButton guardarBoton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField precioText;
	private javax.swing.JTextField referenciaText;
	private javax.swing.JTextField tituloText;
	private javax.swing.JComboBox transaccionBox;

	private DefaultListModel modeloLista;
	private List<Categoria> listCategoria;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">

	public GestionArticulos() {
		super();
		setResizable(false);
		setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
		listCategoria = new ArrayList<Categoria>();

		jPanel1 = new javax.swing.JPanel();
		buscar = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tituloText = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		descripcionArea = new javax.swing.JTextArea();
		referenciaText = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		autorText = new javax.swing.JTextField();
		precioText = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		formatoBox = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		categoria = new javax.swing.JComboBox();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		categoriaList = new javax.swing.JList();
		agregarCat = new javax.swing.JButton();
		eliminarCat = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		transaccionBox = new javax.swing.JComboBox();
		guardarBoton = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		estadoBox = new javax.swing.JComboBox();
		jLabel12 = new javax.swing.JLabel();
		disponibleBox = new javax.swing.JComboBox();
		jPanel3 = new javax.swing.JPanel();
		cancelar = new javax.swing.JButton();
		cancelar.setBounds(16, 363, 113, 23);
		agregar = new javax.swing.JButton();
		agregar.setBounds(27, 27, 113, 23);
		editar = new javax.swing.JButton();
		editar.setBounds(27, 61, 113, 23);

		setTitle("Agregar Artículo");

		jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		buscar.setText("Buscar Artículo");

		jLabel1.setText("Título");

		jLabel4.setText("Descripción");

		tituloText.setEnabled(false);

		jLabel5.setText("Precio");

		jLabel6.setText("Categoria");

		descripcionArea.setColumns(20);
		descripcionArea.setRows(5);
		descripcionArea.setEnabled(false);
		descripcionArea.setFocusable(false);
		descripcionArea.setOpaque(false);
		jScrollPane2.setViewportView(descripcionArea);

		jLabel7.setText("Autor");

		autorText.setEnabled(false);

		precioText.setEnabled(false);

		jLabel9.setText("pesos COL");

		// formatoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CD",
		// "Pelicula", "Libro" }));
		formatoBox.setEnabled(false);

		jLabel2.setText("Referencia");

		// categoriaox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		// "Rock", "Vallenato", "Bolero" }));
		categoria.setEnabled(false);

		jLabel3.setText("Formato");

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Categorías Asociadas"));
		jPanel2.setFocusable(false);
		jPanel2.setName(""); // NOI18N

		modeloLista = new DefaultListModel();
		categoriaList.setModel(modeloLista);

		/*
		 * categoriaList.setModel(new javax.swing.AbstractListModel() { String[] strings
		 * = { "Musical", "Drama", "Suspenso", "Acción" }; public int getSize() { return
		 * strings.length; } public Object getElementAt(int i) { return strings[i]; }
		 * });
		 */
		// categoriaList.setEnabled(false);
		jScrollPane1.setViewportView(categoriaList);

		agregarCat.setText("Agregar");
		agregarCat.setEnabled(false);

		eliminarCat.setText("Eliminar");
		eliminarCat.setEnabled(false);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(agregarCat).addComponent(eliminarCat))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
				new java.awt.Component[] { agregarCat, eliminarCat });

		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addComponent(agregarCat).addGap(16, 16, 16)
						.addComponent(eliminarCat))
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
						javax.swing.GroupLayout.PREFERRED_SIZE));

		jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL,
				new java.awt.Component[] { agregarCat, eliminarCat });

		jLabel10.setText("Transacción");

		// transaccionBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		// "Alquilar", "Vender" }));
		transaccionBox.setEnabled(false);

		guardarBoton.setText("Guardar");
		guardarBoton.setEnabled(false);

		jLabel11.setText("Estado");

		// estadoBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
		// "Bueno", "Regular", "Ligero Deterioro", "Muy Deteriorado" }));
		estadoBox.setEnabled(false);

		jLabel12.setText("Disponibilidad");

		disponibleBox.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Disponible", "Prestado", "Vendido", "Dado de Baja" }));
		disponibleBox.setEnabled(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(12)
							.addComponent(jLabel2))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6)
								.addComponent(jLabel1)
								.addComponent(jLabel7)
								.addComponent(jLabel3)))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel5))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel10))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel11))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jLabel12)))
					.addGap(18)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(transaccionBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
							.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
								.addComponent(referenciaText, GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(buscar, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
								.addGap(8))
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
									.addComponent(formatoBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addComponent(categoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGap(18)
								.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addComponent(autorText)
							.addComponent(tituloText)
							.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(precioText, GroupLayout.PREFERRED_SIZE, 171, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.UNRELATED)
								.addComponent(jLabel9))
							.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(disponibleBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(guardarBoton)
								.addGap(15)))
						.addComponent(estadoBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(referenciaText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2)
						.addComponent(buscar))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel1)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jLabel7)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(jLabel3)
							.addGap(11)
							.addComponent(jLabel6))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(tituloText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(autorText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.UNRELATED)
									.addComponent(formatoBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
									.addGap(11)
									.addComponent(categoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGap(11)
									.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel4)
						.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(precioText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel9)
						.addComponent(jLabel5))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(transaccionBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel10))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(estadoBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel11))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(disponibleBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel12)
						.addComponent(guardarBoton))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel1Layout.linkSize(SwingConstants.VERTICAL, new Component[] {tituloText, autorText});
		jPanel1.setLayout(jPanel1Layout);

		jPanel2.getAccessibleContext().setAccessibleName("");

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones del Menú"));

		cancelar.setText("Cancelar");

		agregar.setText("Agregar Artículo");

		editar.setText("Editar Artículo");
		editar.setEnabled(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(10)
					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(18, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		jPanel3.setLayout(null);
		jPanel3.add(cancelar);
		jPanel3.add(editar);
		jPanel3.add(agregar);
		getContentPane().setLayout(layout);

		pack();
	}

	public JButton getAgregar() {
		return agregar;
	}

	public void setAgregar(JButton agregar) {
		this.agregar = agregar;
	}

	public JButton getAgregarCat() {
		return agregarCat;
	}

	public void setAgregarCat(JButton agregarCat) {
		this.agregarCat = agregarCat;
	}

	public JTextField getAutorText() {
		return autorText;
	}

	public void setAutorText(JTextField autorText) {
		this.autorText = autorText;
	}

	public JButton getBuscar() {
		return buscar;
	}

	public void setBuscar(JButton buscar) {
		this.buscar = buscar;
	}

	public JButton getCancelar() {
		return cancelar;
	}

	public void setCancelar(JButton cancelar) {
		this.cancelar = cancelar;
	}

	public JList getCategoriaList() {
		return categoriaList;
	}

	public void setCategoriaList(JList categoriaList) {
		this.categoriaList = categoriaList;
	}

	public JComboBox getCategoriaox() {
		return categoria;
	}

	public void setCategoriaox(JComboBox categoriaox) {
		this.categoria = categoriaox;
	}

	public JTextArea getDescripcionArea() {
		return descripcionArea;
	}

	public void setDescripcionArea(JTextArea descripcionArea) {
		this.descripcionArea = descripcionArea;
	}

	public JComboBox getDisponibleBox() {
		return disponibleBox;
	}

	public void setDisponibleBox(JComboBox disponibleBox) {
		this.disponibleBox = disponibleBox;
	}

	public JButton getEditar() {
		return editar;
	}

	public void setEditar(JButton editar) {
		this.editar = editar;
	}

	public JButton getEliminarCat() {
		return eliminarCat;
	}

	public void setEliminarCat(JButton eliminarCat) {
		this.eliminarCat = eliminarCat;
	}

	public JComboBox getEstadoBox() {
		return estadoBox;
	}

	public void setEstadoBox(JComboBox estadoBox) {
		this.estadoBox = estadoBox;
	}

	public JComboBox getFormatoBox() {
		return formatoBox;
	}

	public void setFormatoBox(JComboBox formatoBox) {
		this.formatoBox = formatoBox;
	}

	public JButton getGuardarBoton() {
		return guardarBoton;
	}

	public void setGuardarBoton(JButton guardarBoton) {
		this.guardarBoton = guardarBoton;
	}

	public JTextField getPrecioText() {
		return precioText;
	}

	public void setPrecioText(JTextField precioText) {
		this.precioText = precioText;
	}

	public JTextField getReferenciaText() {
		return referenciaText;
	}

	public void setReferenciaText(JTextField referenciaText) {
		this.referenciaText = referenciaText;
	}

	public JTextField getTituloText() {
		return tituloText;
	}

	public void setTituloText(JTextField tituloText) {
		this.tituloText = tituloText;
	}

	public JComboBox getTransaccionBox() {
		return transaccionBox;
	}

	public void setTransaccionBox(JComboBox transaccionBox) {
		this.transaccionBox = transaccionBox;
	}

	public void setControlador(ControladorGestionArticulos controlador) {
		buscar.setActionCommand("Buscar");
		buscar.addActionListener(controlador);

		agregar.setActionCommand("Agregar");
		agregar.addActionListener(controlador);

		editar.setActionCommand("Editar");
		editar.addActionListener(controlador);

		guardarBoton.setActionCommand("Guardar");
		guardarBoton.addActionListener(controlador);

		cancelar.setActionCommand("Cancelar");
		cancelar.addActionListener(controlador);

		agregarCat.setActionCommand("AgregarCat");
		agregarCat.addActionListener(controlador);

		eliminarCat.setActionCommand("EliminarCat");
		eliminarCat.addActionListener(controlador);
	}

	public void mostrarMensajeDialogo(String mensaje) {
		JOptionPane.showMessageDialog(this, mensaje);
	}

	public int mostrarMensajeConfirmacion(String mensaje, String titulo) {
		return JOptionPane.showConfirmDialog(null, mensaje, titulo, JOptionPane.OK_CANCEL_OPTION);
	}

	public DefaultListModel getModeloLista() {
		return modeloLista;
	}

	public void setModeloLista(DefaultListModel modeloLista) {
		this.modeloLista = modeloLista;
	}

	public List<Categoria> getListCategoria() {
		return listCategoria;
	}

	public void setListCategoria(List<Categoria> listCategoria) {
		this.listCategoria = listCategoria;
	}

}
